# Generated by Django 2.0.13 on 2019-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('type', models.CharField(choices=[('PA', 'papa'), ('VR', 'verdura'), ('ET', 'etcetera')], max_length=255, verbose_name='tipo_producto')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio venta')),
                ('Precio_Anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio anterior')),
                ('count_stock', models.IntegerField(default=0, verbose_name='existencia')),
                ('f_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
