# Generated by Django 2.0.13 on 2019-07-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='f_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
