# Generated by Django 2.1.4 on 2019-07-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCompras', '0003_producto_almacen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_almacen',
            old_name='cantidad',
            new_name='cantidadProductos',
        ),
    ]
