# Generated by Django 2.1.4 on 2019-07-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCompras', '0004_auto_20190718_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField()),
                ('CostoTotal', models.DecimalField(decimal_places=20, max_digits=50)),
                ('provehedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloCompras.Provehedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProductos', models.IntegerField()),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloCompras.Compra')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='provehedor',
        ),
        migrations.AddField(
            model_name='compra_producto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloCompras.Producto'),
        ),
    ]
