# Generated by Django 2.1.4 on 2019-07-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCompras', '0005_auto_20190718_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre',
        ),
    ]
